### ISSUE TITLE
how to recompile main.p4 with cpu_port modified ? 

### ISSUE THREAD

**Issue by lxlmummy** [stratum/testvectors#29]
According to  https://github.com/stratum/testvectors/issues/23， I want to change the CPU_PORT value from 192 to 320，so I change the makefile，set “cpu_port_montara := 192” to be “cpu_port_montara := 320”  at compile time. Is that the right thing to do? And If so,  how to modify the testvector related file PipelineConfig.pb.txt，which is located in https://github.com/stratum/testvectors/blob/master/tofino/PipelineConfig.pb.txt ?

**Comment by abhilashendurthi** [comment]
We have another PipelineConfig with filename `PipelineConfig64.pb.txt` is available in the repo which has been built with cpu_port = 320
We don't have a way to generate PipelineConfig dynamically at this point. If you want to create a new PipelineConfig, you can build p4src according to this link: https://github.com/opennetworkinglab/stratum-onos-demo/tree/master/p4src. I will update the instructions to create PipelineConfig from generated p4src fiiles.

**Comment by lxlmummy** [comment]
I am looking forward to your updating the instructions to create PipelineConfig from generated p4src fiiles. I will first try the **PipelineConfig64.pb.txt**

**Comment by lxlmummy** [comment]
@abhilashendurthi , thank you very much，the **PipelineConfig64.pb.txt** works ! After you update the instructions to create PipelineConfig from generated p4src fiile,  I will close this issue.

**Comment by lxlmummy** [comment]
close this issue for https://github.com/stratum/testvectors/issues/30 instead.
